--- #YAML:1.0
name:               RDF-RDFa-Parser-Redland
version:            0.22
abstract:           Parses RDFa into a RDF::Redland::Model.
author:
    - Toby Inkster <mail@tobyinkster.co.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    RDF::RDFa::Parser:  0.11
    RDF::Redland:       1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
