--- #YAML:1.0
name:                RDF-RDFa-Parser-Redland
version:             0.01
abstract:            Parses RDFa into a RDF::Redland::Model.
license:             ~
author:              
    - Toby Inkster <mail@tobyinkster.co.uk>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    RDF::RDFa::Parser:             0.11
    RDF::Redland:                  1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
